### PR TITLE
novactf refactoring

### PR DESCRIPTION
**Pull request by azazellochg**
To be merged after #39 

- fix defocus shift: should be passed in a file for ctf correction, and as a param for reconstruction
- stack is aligned after ctf correction
- fix test tilt axis value
- add astigmatism validation
- do not create new TomoAcquisition object
- use mrc extension for all files

### CODE REVIEW

**Comment by azazellochg** [comment]
Pendind fix for erase gold

**Comment by fede-pe** [comment]
It is crushing to me with the error:

terminate called after throwing an instance of 'ExceptionFileOpen'
what():  Following file could not be opened: Runs/011675_ProtNovaCtfTomoReconstruction/tmp/TS_03/TS_03_filter.mrc_33

That file does no exist. Also I think it is a good idea to keep the behaviour in which compute defocus array protocol triggers the 3d ctf correction and reconstruction

**Comment by azazellochg** [comment]
The crash is because the https://github.com/scipion-em/scipion-em-imod/pull/159 is not merged yet. If you use that branch, the x/y swapping should work properly

**Comment by azazellochg** [comment]
The trigger will now be difficult as the second protocols has more options and needs to make more validations before run..

**Comment by azazellochg** [comment]
Hi @fede-pe , I think I figured out the reason for different number of slices in novactf. defocus files are generated from unaligned ts, while reconstructin is done from aligned one. The aligned has x/y swap, so that's why we get a few more slices. The solution is to input number of files instead of defocus step for reconstruction. I pushed a fix.

**Review by fede-pe — APPROVED** [review]

**Pull request merged**
